/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make changes to this file.
// Regenerate it by running `pnpm build` or `pnpm dev`

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as DemoImport } from './routes/demo'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as SSlugImport } from './routes/s.$slug'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AdminSurveysIndexImport } from './routes/admin/surveys/index'
import { Route as AdminSurveysNewImport } from './routes/admin/surveys/new'
import { Route as AdminSurveysIdImport } from './routes/admin/surveys/$id'
import { Route as AdminSurveysIdResponsesImport } from './routes/admin/surveys/$id/responses'

// Create Virtual Routes

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DemoRoute = DemoImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SSlugRoute = SSlugImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminSurveysIndexRoute = AdminSurveysIndexImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminSurveysNewRoute = AdminSurveysNewImport.update({
  id: '/surveys/new',
  path: '/surveys/new',
  getParentRoute: () => AdminRoute,
} as any)

const AdminSurveysIdRoute = AdminSurveysIdImport.update({
  id: '/surveys/$id',
  path: '/surveys/$id',
  getParentRoute: () => AdminRoute,
} as any)

const AdminSurveysIdResponsesRoute = AdminSurveysIdResponsesImport.update({
  id: '/surveys/$id/responses',
  path: '/surveys/$id/responses',
  getParentRoute: () => AdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/surveys/': {
      id: '/admin/surveys/'
      path: '/surveys/'
      fullPath: '/admin/surveys/'
      preLoaderRoute: typeof AdminSurveysIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/surveys/new': {
      id: '/admin/surveys/new'
      path: '/surveys/new'
      fullPath: '/admin/surveys/new'
      preLoaderRoute: typeof AdminSurveysNewImport
      parentRoute: typeof AdminImport
    }
    '/admin/surveys/$id': {
      id: '/admin/surveys/$id'
      path: '/surveys/$id'
      fullPath: '/admin/surveys/$id'
      preLoaderRoute: typeof AdminSurveysIdImport
      parentRoute: typeof AdminImport
    }
    '/admin/surveys/$id/responses': {
      id: '/admin/surveys/$id/responses'
      path: '/surveys/$id/responses'
      fullPath: '/admin/surveys/$id/responses'
      preLoaderRoute: typeof AdminSurveysIdResponsesImport
      parentRoute: typeof AdminImport
    }
  }
}

// Create and export the route tree

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSurveysIndexRoute: typeof AdminSurveysIndexRoute
  AdminSurveysNewRoute: typeof AdminSurveysNewRoute
  AdminSurveysIdRoute: typeof AdminSurveysIdRoute
  AdminSurveysIdResponsesRoute: typeof AdminSurveysIdResponsesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminSurveysIndexRoute: AdminSurveysIndexRoute,
  AdminSurveysNewRoute: AdminSurveysNewRoute,
  AdminSurveysIdRoute: AdminSurveysIdRoute,
  AdminSurveysIdResponsesRoute: AdminSurveysIdResponsesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/s/$slug': typeof SSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
  '/admin/surveys/new': typeof AdminSurveysNewRoute
  '/admin/surveys/$id': typeof AdminSurveysIdRoute
  '/admin/surveys/$id/responses': typeof AdminSurveysIdResponsesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/s/$slug': typeof SSlugRoute
  '/admin/surveys': typeof AdminSurveysIndexRoute
  '/admin/surveys/new': typeof AdminSurveysNewRoute
  '/admin/surveys/$id': typeof AdminSurveysIdRoute
  '/admin/surveys/$id/responses': typeof AdminSurveysIdResponsesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/s/$slug': typeof SSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
  '/admin/surveys/new': typeof AdminSurveysNewRoute
  '/admin/surveys/$id': typeof AdminSurveysIdRoute
  '/admin/surveys/$id/responses': typeof AdminSurveysIdResponsesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/demo'
    | '/login'
    | '/register'
    | '/s/$slug'
    | '/admin/'
    | '/admin/surveys/'
    | '/admin/surveys/new'
    | '/admin/surveys/$id'
    | '/admin/surveys/$id/responses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/demo'
    | '/login'
    | '/register'
    | '/s/$slug'
    | '/admin/surveys'
    | '/admin/surveys/new'
    | '/admin/surveys/$id'
    | '/admin/surveys/$id/responses'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/demo'
    | '/login'
    | '/register'
    | '/s/$slug'
    | '/admin/'
    | '/admin/surveys/'
    | '/admin/surveys/new'
    | '/admin/surveys/$id'
    | '/admin/surveys/$id/responses'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SSlugRoute: typeof SSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SSlugRoute: SSlugRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/demo",
        "/login",
        "/register",
        "/s/$slug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/",
        "/admin/surveys/",
        "/admin/surveys/new",
        "/admin/surveys/$id",
        "/admin/surveys/$id/responses"
      ]
    },
    "/demo": {
      "filePath": "demo.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/s/$slug": {
      "filePath": "s.$slug.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/admin/surveys/": {
      "filePath": "admin/surveys/index.tsx",
      "parent": "/admin"
    },
    "/admin/surveys/new": {
      "filePath": "admin/surveys/new.tsx",
      "parent": "/admin"
    },
    "/admin/surveys/$id": {
      "filePath": "admin/surveys/$id.tsx",
      "parent": "/admin"
    },
    "/admin/surveys/$id/responses": {
      "filePath": "admin/surveys/$id.responses.tsx",
      "parent": "/admin"
    }
  }
}
ROUTE_MANIFEST_END */
